### PR TITLE
Ignore PHP startup errors

### LINKED ISSUE #33: Successful lint with PHP startup errors should exit with 0 not 254
I am not sure exactly what the problem is, but parallel-lint exits with "Error in skip-linting.php process" on php 8, you can check the full output at https://travis-ci.org/github/Seldaek/monolog/jobs/689943262#L395

### PR DESCRIPTION
**Pull request by jrfnl**
Ignoring PHP startup errors completely for any PHP processes started from within the application.

Fixes #33

### CODE REVIEW

**Comment by jrfnl** [comment]
@grogy Anything I can do to move this PR forward ?

**Comment by jrfnl** [comment]
@grogy Any chance of this PR getting some love ?

**Comment by grogy** [comment]
I read previous thread https://github.com/php-parallel-lint/PHP-Parallel-Lint/issues/33 and current I think about it is good thing in project. Maybe it make the sence.. please, take me a few days for it.

Idea - is good when tool does second thing - silence warnings?

**Comment by grogy** [comment]
My thinking about this change takes long. I am sorry, but I cannot merge everything that will be created in PRs.

It makes sense to me. Reason - directive `display-startup-errors` is for debugging and in Lint we do not need other extensions (only json, but currently PHP versions include JSON-extension).

Thank you @Seldaek for define problem and @jrfnl for implementation and kick me for resolve PR :)

**Pull request merged**
