### PR TITLE
Move to supporting Box v3

### LINKED ISSUE #36: Make box config compatible with humbug/box
The box package maintained in the humbug organisation is the newest version of box (known as box3) being maintained by the community:

https://github.com/humbug/box

It would be great if we could get a new release that contained a box config file compatible with box3.

Alternatively, perhaps the maintainers of this package could provide a phar (hopefully with the php-console-highlighter package included) in the github releases section.

### PR DESCRIPTION
**Pull request by mwgamble**
Box v2 has been out of support for a very long time.

Fixes #36

### CODE REVIEW

**Comment by mwgamble** [comment]
Is it really still necessary to support PHP 5.4? It's been end-of-life for a long time now.

**Comment by jrfnl** [comment]
> Is it really still necessary to support PHP 5.4? It's been end-of-life for a long time now.

As this is a linting tool which is used in the CI/QA toolset for other projects, supporting a wide range of PHP versions, IMHO, is a good thing and something which makes this the tool of choice.

**Comment by mwgamble** [comment]
Fair enough. I'll push an update shortly that removes the use of `::class`.

**Comment by mwgamble** [comment]
The issue with the PHP 5.4 CI run seems unrelated to my changes. I'm not sure how to proceed.

**Comment by mfn** [comment]
> The issue with the PHP 5.4 CI run seems unrelated to my changes. I'm not sure how to proceed.

I found https://github.com/birgire/geo-query/pull/13#pullrequestreview-143563116 , also the follow up comment seems insightful.

Seems due to missing support for some things, in PHP < 5.6 there's some manual TLS verification going on in composer not working out.

**Comment by grogy** [comment]
I tried it rebase to master and CI looks ok, via https://travis-ci.org/github/php-parallel-lint/PHP-Parallel-Lint/builds/726418723

**Comment by grogy** [comment]
Changes looks ok. Can you update readme, please? - https://github.com/php-parallel-lint/PHP-Parallel-Lint#create-phar-package

**Comment by grogy** [comment]
Ping @mwgamble  :-)

**Comment by mwgamble** [comment]
Apologies, I've changed jobs since I first put this together and haven't had a chance to look at it since then. I'll try to take a look over the weekend.

**Comment by alasdairdc** [comment]
@mwgamble Last box version I can build with (using PHP 7.3) is 3.5.0.  Do you remember what version you used?

**Comment by grogy** [comment]
When you will rebase it please consider that we run phar build in [Github Actions](https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/master/.github/workflows/release.yml#L27)

**Comment by mwgamble** [comment]
I'm sorry, I don't know when I'll be able to work on this again. I'm not really working with PHP at the moment and I don't have access to the repository I was working on. Someone else will need to take up the mantle.

**Comment by grogy** [comment]
@mwgamble solve PR [#70] from @jrfnl Thank you for the example of solution :-)

**Pull request closed without merging**
