### PR TITLE
Use HTML-escaped messages in CheckstyleOutput

### PR DESCRIPTION
**Pull request by gmazzap**
See #72 for details.

### CODE REVIEW

**Comment by jrfnl** [comment]
@gmazzap Nice find!

Just wondering: is there any particular reason to _escape_ the message instead of passing it in `CDATA` markers ?

**Comment by gmazzap** [comment]
No particular reason. Both are valid options IMO and I could change the PR to use CDATA if that's preferred.

**Review by jrfnl — APPROVED** [review]
Thanks @gmazzap !

**Comment by jrfnl** [comment]
Hmm... looks like there is still an issue with this fix on PHP 5.3-5.4. Looking into it now.

**Comment by jrfnl** [comment]
Fixed it, Should be okay now

**Pull request merged**
