### PR TITLE
Tests: add dedicated test for the `SyntaxError::getLine()` method

### PR DESCRIPTION
**Pull request by jrfnl**
This safeguards and documents the current behaviour of the method.

Includes removing redundant conditional in the original method.

### CODE REVIEW

**Comment by jrfnl** [comment]
Build failure is unrelated to this PR. See #116 

I will rebase this PR to show a passing build once PR #116 has been merged and cherrypicked to the `develop` branch.

**Review by grogy — APPROVED** [review]
Perfect messages for parsing. Thank you

**Comment by grogy** [comment]
Can you please rebase this PR? After I can merge it :-)

**Comment by jrfnl** [comment]
Rebased without changes.

**Pull request merged**
