### PR TITLE
Add .github folder to .gitattributes export-ignore

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Review by jrfnl — APPROVED** [review]

**Review by glensc — APPROVED** [review]

**Comment by glensc** [comment]
LGTM

**Comment by grogy** [comment]
Thank you

**Comment by glensc** [comment]
incorrectly attributed as @glensc in changelog:
- https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/d1ad5c76a20bd17f1587d2cb903848b024964b54/CHANGELOG.md

> Add .github folder to .gitattributes export-ignore #54 from @glensc.

**Comment by grogy** [comment]
Fixed, thank you @glensc https://github.com/php-parallel-lint/PHP-Parallel-Lint/blob/eb41d41cc65ceea07a25f37bdaaa21bde7660ad1/CHANGELOG.md

**Pull request merged**
